/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package be.k0suke.titogglekeyboard;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import android.content.Context;
import android.view.inputmethod.InputMethodManager;

@Kroll.module(name="Titogglekeyboard", id="be.k0suke.titogglekeyboard")
public class TitogglekeyboardModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "TitogglekeyboardModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public TitogglekeyboardModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public String show()
	{
		Context context = TiApplication.getInstance().getApplicationContext();
		InputMethodManager manager = (InputMethodManager)context.getSystemService(Context.INPUT_METHOD_SERVICE);
		manager.toggleSoftInput(1, InputMethodManager.SHOW_IMPLICIT);

		return "show";
	}

	@Kroll.method
	public String hide()
	{
		Context context = TiApplication.getInstance().getApplicationContext();
		InputMethodManager manager = (InputMethodManager)context.getSystemService(Context.INPUT_METHOD_SERVICE);
		manager.toggleSoftInput(InputMethodManager.HIDE_IMPLICIT_ONLY, 0);

		return "hidde";
	}

	@Kroll.method
	public String toggle()
	{
		Context context = TiApplication.getInstance().getApplicationContext();
		InputMethodManager manager = (InputMethodManager)context.getSystemService(Context.INPUT_METHOD_SERVICE);
		if (manager.isActive()) {
			manager.toggleSoftInput(InputMethodManager.HIDE_IMPLICIT_ONLY, 0);
		} else {
			manager.toggleSoftInput(1, InputMethodManager.SHOW_IMPLICIT);
		}

		return "toggle";
	}
}